apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-agent
  namespace: default

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jenkins-admin-role
rules:
  # 1. Droits standards (Apps, Services, etc.)
  - apiGroups: ["", "apps", "networking.k8s.io", "batch", "extensions"]
    resources: ["deployments", "services", "statefulsets", "secrets", "ingresses", "persistentvolumeclaims", "pods", "configmaps", "pods/log"]
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]

  # 2. Droits Monitoring (Prometheus)
  - apiGroups: ["monitoring.coreos.com"]
    resources: ["servicemonitors"]
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]

  # 3. DROITS AUTOSCALING (HPA) - C'est ce qui manque !
  - apiGroups: ["autoscaling"]
    resources: ["horizontalpodautoscalers"]
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jenkins-admin-binding
subjects:
  - kind: ServiceAccount
    name: jenkins-agent
    namespace: default
roleRef:
  kind: ClusterRole
  name: jenkins-admin-role
  apiGroup: rbac.authorization.k8s.io